---
title: "lab 3"
author: "Priscilla Hu  ID:3035385926"
date: "9/23/2019"
output: html_document
---

```{r setup, include=FALSE}
getwd()
setwd("/Users/priscilla/Desktop/UC Berkeley/Stat 154/lab_csv")
```


## Part 1: Minimizing a quadratic

```{r}
#In this exercise, we will be interested in minimizing the quadratic f (x) = 0.5*(x − 2)^2 + 1 using gradient descent.

# 1.1
f <- function(x){
  return(0.5*(x-2)^2 + 1)
}
df<- function(x){
  return(x-2)
}
f(2)

plot(f,xlim=c(-4,8))
plot(df,xlim=c(-4,8))
```

```{r}
# 1.2 
# 1. choose x0
x0=rnorm(n=1)

# 2. implement the gradient descent algorithm
x=x0
for (t in 1:10){
  x=x-df(x)
}
x
```


```{r}
# 1.3 1x⊤Ax−b⊤x
A=matrix(c(1,0,0,2),nrow=2,ncol=2)
b=matrix(c(1,1),nrow=2)
f1 <- function(x){
  return(0.5*t(x)%*%A%*%x-t(b)%*%x)
}
df1<-function(x){
  return(A%*%x-b)
}

x=matrix(rnorm(n=2))
for (t in 1:100){
  x=x-0.1*df(x)
}
x
```


## Part 2: OLS Regression

```{r}
mtcars=read.csv("mtcars.csv",header=T)
response <- 'mpg'
predictors <- c('hp', 'qsec', 'wt')
M <- as.matrix(mtcars[ ,predictors])
X <- cbind(intercept = 1, M)
y <- mtcars[ ,response]

```

```{r}
# 2.1
l<-function(b){
  return(t(X%*%b-y)%*%(X%*%b-y)/nrow(X))
}
l_gradient<-function(b){
  return((2*t(X)%*%X%*%b-2*t(X)%*%y)/nrow(X))
}
```

```{r}
#2.2
b=matrix(rnorm(n=4))
MSE=matrix(nrow=500,ncol=1)
mse=c()
for (t in 1:500){
  b=b-0.00001*l_gradient(b)
  A=(y-X%*%b)
  MSE[t]=t(A)%*%A/nrow(X)
  mse=c(mse,l(b))
}
b
```


## Part 3: Stochastic Gradient Descent

```{r}
# 3.1 Implement a function sample_batch(n, B)
sample_batch<- function(n, B){
  return(sample(n,B,replace=F))
}
l<-function(b){
  select=sample_batch(nrow(X),16)
  X1=X[select,]
  y1=y[select,]
  return(t(X1%*%b-y1)%*%(X1%*%b-y1)/nrow(X))
}
l_gradient<-function(b){
  select=sample_batch(nrow(X),16)
  X1=X[select,]
  y1=y[select]
  return((2*t(X1)%*%X1%*%b-2*t(X1)%*%y1)/nrow(X))
}
```
```{r}
# 3.2 implement stochastic gradient descent for the sample problem as in Part 2
MSE=matrix(nrow=500,ncol=1)
b=matrix(rnorm(n=4))
for (t in 1:500){
  b=b-0.00001*l_gradient(b)
  A=(y-X%*%b)^2
  MSE[t]=t(A)%*%A/nrow(X)
}
b
```

```{r}
plot(1:500,MSE,ylim=c(50000,1000000))
```

